// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.DataAccess;

namespace MyApp.Migrations
{
    [DbContext(typeof(StatementContext))]
    [Migration("20210607102305_newMigration")]
    partial class newMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyApp.Models.StatementModel", b =>
                {
                    b.Property<long>("statementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("statementImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("statementName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("statementId");

                    b.HasIndex("statementName");

                    b.ToTable("Statements");
                });
#pragma warning restore 612, 618
        }
    }
}
